// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: logsys/v1/logsys.proto

package logsysv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogEntry mirrors logsys.LogEntry — the same data crossing every
// transport (REST, gRPC, WebSocket) is this one shape.
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Fields        *structpb.Struct       `protobuf:"bytes,4,opt,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_logsys_v1_logsys_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_logsys_v1_logsys_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_logsys_v1_logsys_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() *structpb.Struct {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ReadLogs / ClearLogs mirror the GET/DELETE /logs REST endpoints —
// same underlying logsys.Manager, different wire protocol.
type ReadLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=until,proto3" json:"until,omitempty"`
	Contains      string                 `protobuf:"bytes,4,opt,name=contains,proto3" json:"contains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLogsRequest) Reset() {
	*x = ReadLogsRequest{}
	mi := &file_logsys_v1_logsys_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLogsRequest) ProtoMessage() {}

func (x *ReadLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsys_v1_logsys_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLogsRequest.ProtoReflect.Descriptor instead.
func (*ReadLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsys_v1_logsys_proto_rawDescGZIP(), []int{1}
}

func (x *ReadLogsRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ReadLogsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ReadLogsRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *ReadLogsRequest) GetContains() string {
	if x != nil {
		return x.Contains
	}
	return ""
}

type ReadLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLogsResponse) Reset() {
	*x = ReadLogsResponse{}
	mi := &file_logsys_v1_logsys_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLogsResponse) ProtoMessage() {}

func (x *ReadLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsys_v1_logsys_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLogsResponse.ProtoReflect.Descriptor instead.
func (*ReadLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsys_v1_logsys_proto_rawDescGZIP(), []int{2}
}

func (x *ReadLogsResponse) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ClearLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLogsRequest) Reset() {
	*x = ClearLogsRequest{}
	mi := &file_logsys_v1_logsys_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLogsRequest) ProtoMessage() {}

func (x *ClearLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsys_v1_logsys_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLogsRequest.ProtoReflect.Descriptor instead.
func (*ClearLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsys_v1_logsys_proto_rawDescGZIP(), []int{3}
}

func (x *ClearLogsRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

type ClearLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearLogsResponse) Reset() {
	*x = ClearLogsResponse{}
	mi := &file_logsys_v1_logsys_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearLogsResponse) ProtoMessage() {}

func (x *ClearLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsys_v1_logsys_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearLogsResponse.ProtoReflect.Descriptor instead.
func (*ClearLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsys_v1_logsys_proto_rawDescGZIP(), []int{4}
}

// StreamContainerLogs mirrors GET /containers/{id}/logs/stream (SSE) —
// same ContainerService.StreamLogs underneath, server-streaming gRPC
// instead of an event stream.
type StreamContainerLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Tail          string                 `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContainerLogsRequest) Reset() {
	*x = StreamContainerLogsRequest{}
	mi := &file_logsys_v1_logsys_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerLogsRequest) ProtoMessage() {}

func (x *StreamContainerLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_logsys_v1_logsys_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContainerLogsRequest.ProtoReflect.Descriptor instead.
func (*StreamContainerLogsRequest) Descriptor() ([]byte, []int) {
	return file_logsys_v1_logsys_proto_rawDescGZIP(), []int{5}
}

func (x *StreamContainerLogsRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StreamContainerLogsRequest) GetTail() string {
	if x != nil {
		return x.Tail
	}
	return ""
}

type StreamContainerLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Line          string                 `protobuf:"bytes,1,opt,name=line,proto3" json:"line,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamContainerLogsResponse) Reset() {
	*x = StreamContainerLogsResponse{}
	mi := &file_logsys_v1_logsys_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamContainerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamContainerLogsResponse) ProtoMessage() {}

func (x *StreamContainerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_logsys_v1_logsys_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamContainerLogsResponse.ProtoReflect.Descriptor instead.
func (*StreamContainerLogsResponse) Descriptor() ([]byte, []int) {
	return file_logsys_v1_logsys_proto_rawDescGZIP(), []int{6}
}

func (x *StreamContainerLogsResponse) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

var File_logsys_v1_logsys_proto protoreflect.FileDescriptor

const file_logsys_v1_logsys_proto_rawDesc = "" +
	"\n" +
	"\x16logsys/v1/logsys.proto\x12\tlogsys.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x01\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05level\x18\x02 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12/\n" +
	"\x06fields\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x06fields\"\xa7\x01\n" +
	"\x0fReadLogsRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x120\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12\x1a\n" +
	"\bcontains\x18\x04 \x01(\tR\bcontains\"A\n" +
	"\x10ReadLogsResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.logsys.v1.LogEntryR\aentries\"F\n" +
	"\x10ClearLogsRequest\x122\n" +
	"\x06before\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\"\x13\n" +
	"\x11ClearLogsResponse\"S\n" +
	"\x1aStreamContainerLogsRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04tail\x18\x02 \x01(\tR\x04tail\"1\n" +
	"\x1bStreamContainerLogsResponse\x12\x12\n" +
	"\x04line\x18\x01 \x01(\tR\x04line2\x81\x02\n" +
	"\n" +
	"LogService\x12C\n" +
	"\bReadLogs\x12\x1a.logsys.v1.ReadLogsRequest\x1a\x1b.logsys.v1.ReadLogsResponse\x12F\n" +
	"\tClearLogs\x12\x1b.logsys.v1.ClearLogsRequest\x1a\x1c.logsys.v1.ClearLogsResponse\x12f\n" +
	"\x13StreamContainerLogs\x12%.logsys.v1.StreamContainerLogsRequest\x1a&.logsys.v1.StreamContainerLogsResponse0\x01B@Z>contogether/container-api/internal/genproto/logsys/v1;logsysv1b\x06proto3"

var (
	file_logsys_v1_logsys_proto_rawDescOnce sync.Once
	file_logsys_v1_logsys_proto_rawDescData []byte
)

func file_logsys_v1_logsys_proto_rawDescGZIP() []byte {
	file_logsys_v1_logsys_proto_rawDescOnce.Do(func() {
		file_logsys_v1_logsys_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logsys_v1_logsys_proto_rawDesc), len(file_logsys_v1_logsys_proto_rawDesc)))
	})
	return file_logsys_v1_logsys_proto_rawDescData
}

var file_logsys_v1_logsys_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_logsys_v1_logsys_proto_goTypes = []any{
	(*LogEntry)(nil),                    // 0: logsys.v1.LogEntry
	(*ReadLogsRequest)(nil),             // 1: logsys.v1.ReadLogsRequest
	(*ReadLogsResponse)(nil),            // 2: logsys.v1.ReadLogsResponse
	(*ClearLogsRequest)(nil),            // 3: logsys.v1.ClearLogsRequest
	(*ClearLogsResponse)(nil),           // 4: logsys.v1.ClearLogsResponse
	(*StreamContainerLogsRequest)(nil),  // 5: logsys.v1.StreamContainerLogsRequest
	(*StreamContainerLogsResponse)(nil), // 6: logsys.v1.StreamContainerLogsResponse
	(*timestamppb.Timestamp)(nil),       // 7: google.protobuf.Timestamp
	(*structpb.Struct)(nil),             // 8: google.protobuf.Struct
}
var file_logsys_v1_logsys_proto_depIdxs = []int32{
	7, // 0: logsys.v1.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	8, // 1: logsys.v1.LogEntry.fields:type_name -> google.protobuf.Struct
	7, // 2: logsys.v1.ReadLogsRequest.since:type_name -> google.protobuf.Timestamp
	7, // 3: logsys.v1.ReadLogsRequest.until:type_name -> google.protobuf.Timestamp
	0, // 4: logsys.v1.ReadLogsResponse.entries:type_name -> logsys.v1.LogEntry
	7, // 5: logsys.v1.ClearLogsRequest.before:type_name -> google.protobuf.Timestamp
	1, // 6: logsys.v1.LogService.ReadLogs:input_type -> logsys.v1.ReadLogsRequest
	3, // 7: logsys.v1.LogService.ClearLogs:input_type -> logsys.v1.ClearLogsRequest
	5, // 8: logsys.v1.LogService.StreamContainerLogs:input_type -> logsys.v1.StreamContainerLogsRequest
	2, // 9: logsys.v1.LogService.ReadLogs:output_type -> logsys.v1.ReadLogsResponse
	4, // 10: logsys.v1.LogService.ClearLogs:output_type -> logsys.v1.ClearLogsResponse
	6, // 11: logsys.v1.LogService.StreamContainerLogs:output_type -> logsys.v1.StreamContainerLogsResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_logsys_v1_logsys_proto_init() }
func file_logsys_v1_logsys_proto_init() {
	if File_logsys_v1_logsys_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logsys_v1_logsys_proto_rawDesc), len(file_logsys_v1_logsys_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_logsys_v1_logsys_proto_goTypes,
		DependencyIndexes: file_logsys_v1_logsys_proto_depIdxs,
		MessageInfos:      file_logsys_v1_logsys_proto_msgTypes,
	}.Build()
	File_logsys_v1_logsys_proto = out.File
	file_logsys_v1_logsys_proto_goTypes = nil
	file_logsys_v1_logsys_proto_depIdxs = nil
}
