// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: logsys/v1/logsys.proto

package logsysv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	v1 "contogether/container-api/internal/genproto/logsys/v1"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LogServiceName is the fully-qualified name of the LogService service.
	LogServiceName = "logsys.v1.LogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LogServiceReadLogsProcedure is the fully-qualified name of the LogService's ReadLogs RPC.
	LogServiceReadLogsProcedure = "/logsys.v1.LogService/ReadLogs"
	// LogServiceClearLogsProcedure is the fully-qualified name of the LogService's ClearLogs RPC.
	LogServiceClearLogsProcedure = "/logsys.v1.LogService/ClearLogs"
	// LogServiceStreamContainerLogsProcedure is the fully-qualified name of the LogService's
	// StreamContainerLogs RPC.
	LogServiceStreamContainerLogsProcedure = "/logsys.v1.LogService/StreamContainerLogs"
)

// LogServiceClient is a client for the logsys.v1.LogService service.
type LogServiceClient interface {
	ReadLogs(context.Context, *connect.Request[v1.ReadLogsRequest]) (*connect.Response[v1.ReadLogsResponse], error)
	ClearLogs(context.Context, *connect.Request[v1.ClearLogsRequest]) (*connect.Response[v1.ClearLogsResponse], error)
	StreamContainerLogs(context.Context, *connect.Request[v1.StreamContainerLogsRequest]) (*connect.ServerStreamForClient[v1.StreamContainerLogsResponse], error)
}

// NewLogServiceClient constructs a client for the logsys.v1.LogService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	logServiceMethods := v1.File_logsys_v1_logsys_proto.Services().ByName("LogService").Methods()
	return &logServiceClient{
		readLogs: connect.NewClient[v1.ReadLogsRequest, v1.ReadLogsResponse](
			httpClient,
			baseURL+LogServiceReadLogsProcedure,
			connect.WithSchema(logServiceMethods.ByName("ReadLogs")),
			connect.WithClientOptions(opts...),
		),
		clearLogs: connect.NewClient[v1.ClearLogsRequest, v1.ClearLogsResponse](
			httpClient,
			baseURL+LogServiceClearLogsProcedure,
			connect.WithSchema(logServiceMethods.ByName("ClearLogs")),
			connect.WithClientOptions(opts...),
		),
		streamContainerLogs: connect.NewClient[v1.StreamContainerLogsRequest, v1.StreamContainerLogsResponse](
			httpClient,
			baseURL+LogServiceStreamContainerLogsProcedure,
			connect.WithSchema(logServiceMethods.ByName("StreamContainerLogs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// logServiceClient implements LogServiceClient.
type logServiceClient struct {
	readLogs            *connect.Client[v1.ReadLogsRequest, v1.ReadLogsResponse]
	clearLogs           *connect.Client[v1.ClearLogsRequest, v1.ClearLogsResponse]
	streamContainerLogs *connect.Client[v1.StreamContainerLogsRequest, v1.StreamContainerLogsResponse]
}

// ReadLogs calls logsys.v1.LogService.ReadLogs.
func (c *logServiceClient) ReadLogs(ctx context.Context, req *connect.Request[v1.ReadLogsRequest]) (*connect.Response[v1.ReadLogsResponse], error) {
	return c.readLogs.CallUnary(ctx, req)
}

// ClearLogs calls logsys.v1.LogService.ClearLogs.
func (c *logServiceClient) ClearLogs(ctx context.Context, req *connect.Request[v1.ClearLogsRequest]) (*connect.Response[v1.ClearLogsResponse], error) {
	return c.clearLogs.CallUnary(ctx, req)
}

// StreamContainerLogs calls logsys.v1.LogService.StreamContainerLogs.
func (c *logServiceClient) StreamContainerLogs(ctx context.Context, req *connect.Request[v1.StreamContainerLogsRequest]) (*connect.ServerStreamForClient[v1.StreamContainerLogsResponse], error) {
	return c.streamContainerLogs.CallServerStream(ctx, req)
}

// LogServiceHandler is an implementation of the logsys.v1.LogService service.
type LogServiceHandler interface {
	ReadLogs(context.Context, *connect.Request[v1.ReadLogsRequest]) (*connect.Response[v1.ReadLogsResponse], error)
	ClearLogs(context.Context, *connect.Request[v1.ClearLogsRequest]) (*connect.Response[v1.ClearLogsResponse], error)
	StreamContainerLogs(context.Context, *connect.Request[v1.StreamContainerLogsRequest], *connect.ServerStream[v1.StreamContainerLogsResponse]) error
}

// NewLogServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLogServiceHandler(svc LogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	logServiceMethods := v1.File_logsys_v1_logsys_proto.Services().ByName("LogService").Methods()
	logServiceReadLogsHandler := connect.NewUnaryHandler(
		LogServiceReadLogsProcedure,
		svc.ReadLogs,
		connect.WithSchema(logServiceMethods.ByName("ReadLogs")),
		connect.WithHandlerOptions(opts...),
	)
	logServiceClearLogsHandler := connect.NewUnaryHandler(
		LogServiceClearLogsProcedure,
		svc.ClearLogs,
		connect.WithSchema(logServiceMethods.ByName("ClearLogs")),
		connect.WithHandlerOptions(opts...),
	)
	logServiceStreamContainerLogsHandler := connect.NewServerStreamHandler(
		LogServiceStreamContainerLogsProcedure,
		svc.StreamContainerLogs,
		connect.WithSchema(logServiceMethods.ByName("StreamContainerLogs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/logsys.v1.LogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LogServiceReadLogsProcedure:
			logServiceReadLogsHandler.ServeHTTP(w, r)
		case LogServiceClearLogsProcedure:
			logServiceClearLogsHandler.ServeHTTP(w, r)
		case LogServiceStreamContainerLogsProcedure:
			logServiceStreamContainerLogsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLogServiceHandler struct{}

func (UnimplementedLogServiceHandler) ReadLogs(context.Context, *connect.Request[v1.ReadLogsRequest]) (*connect.Response[v1.ReadLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("logsys.v1.LogService.ReadLogs is not implemented"))
}

func (UnimplementedLogServiceHandler) ClearLogs(context.Context, *connect.Request[v1.ClearLogsRequest]) (*connect.Response[v1.ClearLogsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("logsys.v1.LogService.ClearLogs is not implemented"))
}

func (UnimplementedLogServiceHandler) StreamContainerLogs(context.Context, *connect.Request[v1.StreamContainerLogsRequest], *connect.ServerStream[v1.StreamContainerLogsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("logsys.v1.LogService.StreamContainerLogs is not implemented"))
}
